# Jekyll configuration for GitHub Pages

# Site settings
title: LoRA Craft
description: Craft your own LoRA adapters with LoRA Craft - A web-based interface for fine-tuning language models using GRPO
url: "https://jwest33.github.io"
baseurl: "/lora_craft"

# Theme
theme: jekyll-theme-cayman
# Alternative themes:
# - jekyll-theme-minimal
# - jekyll-theme-slate
# - jekyll-theme-architect

# Repository information
repository: jwest33/lora_craft
github:
  repository_url: https://github.com/jwest33/lora_craft

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-relative-links

# Enable relative links
relative_links:
  enabled: true
  collections: false

# Exclude files from build
exclude:
  - "*.py"
  - "qwen3_(4b)_grpo.py"
  - "gpt_oss_(20b)_grpo.py"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
